// Validates curriculum, question bank, labs, incidents and projects from the real data files.
// Usage: node scripts/validate-content.mjs [--level 03] [--write-report] [--quiet]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { loadContent } from '../src/data/index.js';
import { validateCurriculum, validateQuestionBank, validateLabs, validateIncidents, validateProjects } from '../src/core/schema.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const levelFilter = args.includes('--level') ? `L${String(args[args.indexOf('--level') + 1]).padStart(2, '0')}` : null;
const quiet = args.includes('--quiet');

async function optional(rel, name) {
  const file = path.join(root, rel);
  if (!fs.existsSync(file)) return null;
  const mod = await import(pathToFileURL(file).href);
  return mod[name] ?? mod.default;
}

const { curriculum, bank, errors: loadErrors } = await loadContent();
const issues = [];
for (const e of loadErrors) issues.push({ severity: levelFilter ? 'warning' : 'error', code: 'load', id: 'loader', message: e });
issues.push(...validateCurriculum(curriculum));
const { issues: qIssues, stats } = validateQuestionBank(bank, curriculum);
issues.push(...qIssues);
const lessonIds = new Set(curriculum.flatMap(l => l.modules.flatMap(m => m.lessons.map(x => x.id))));
const labs = await optional('src/data/labs.js', 'LABS');
const incidents = await optional('src/data/incidents.js', 'INCIDENTS');
const projects = await optional('src/data/projects.js', 'PROJECTS');
if (labs) issues.push(...validateLabs(labs, lessonIds));
if (incidents) issues.push(...validateIncidents(incidents));
if (projects) issues.push(...validateProjects(projects, lessonIds));

let shown = issues;
if (levelFilter) shown = issues.filter(i => String(i.id).startsWith(levelFilter) || (i.code === 'load' && i.message.includes(`Level ${Number(levelFilter.slice(1))}:`)) || i.message.includes(`level ${Number(levelFilter.slice(1))}:`));
const errs = shown.filter(i => i.severity === 'error');
const warns = shown.filter(i => i.severity === 'warning');
if (!quiet) for (const i of shown) console.log(`${i.severity.toUpperCase().padEnd(7)} ${i.code.padEnd(16)} ${i.id}: ${i.message}`);

console.log('\n=== Content summary (computed from data files) ===');
console.log(`Levels: ${curriculum.length} | Modules: ${curriculum.reduce((s, l) => s + l.modules.length, 0)} | Lessons: ${lessonIds.size} | Questions: ${stats.total}`);
console.log(`Difficulty: ${JSON.stringify(stats.byDifficulty)} | Multi-select: ${stats.multi} | Practical share: ${(stats.practicalShare * 100).toFixed(1)}%`);
for (const l of stats.levels) {
  if (levelFilter && l.id !== levelFilter) continue;
  console.log(`${l.id} ${l.title}: ${l.total} Qs [${l.modules.map(m => `${m.id.split('-')[1]}:${m.total}`).join(' ')}] diff ${l.byDifficulty.beginner}/${l.byDifficulty.intermediate}/${l.byDifficulty.advanced} practical ${l.practical} multi ${l.multi}`);
}
if (labs) console.log(`Labs: ${labs.length}`);
if (incidents) console.log(`Incidents: ${incidents.length}`);
if (projects) console.log(`Projects: ${projects.length}`);
console.log(`\n${errs.length} error(s), ${warns.length} warning(s)${levelFilter ? ` for ${levelFilter}` : ''}`);

if (args.includes('--write-report')) {
  const lines = ['# Question Bank & Content Report', '', `Generated by \`npm run report\` from the data files on ${new Date().toISOString().slice(0, 10)}. All numbers are counted from the repository data, not estimated.`, '',
    `- Levels: **${curriculum.length}**`, `- Modules: **${curriculum.reduce((s, l) => s + l.modules.length, 0)}**`, `- Lessons: **${lessonIds.size}**`, `- MCQs: **${stats.total}** (multi-select: ${stats.multi})`,
    `- Difficulty: beginner ${stats.byDifficulty.beginner}, intermediate ${stats.byDifficulty.intermediate}, advanced ${stats.byDifficulty.advanced}`,
    `- Practical / output / troubleshooting / scenario share: **${(stats.practicalShare * 100).toFixed(1)}%**`,
    `- Terminal labs: ${labs?.length ?? 0} | Incident scenarios: ${incidents?.length ?? 0} | Projects: ${projects?.length ?? 0}`,
    `- Validation: ${issues.filter(i => i.severity === 'error').length} errors, ${issues.filter(i => i.severity === 'warning').length} warnings`, '',
    '## Per level and module', '', '| Level | Title | Questions | Beginner/Intermediate/Advanced | Practical | Multi | Modules (questions) |', '|---|---|---|---|---|---|---|'];
  for (const l of stats.levels) lines.push(`| ${l.id} | ${l.title} | ${l.total} | ${l.byDifficulty.beginner}/${l.byDifficulty.intermediate}/${l.byDifficulty.advanced} | ${l.practical} | ${l.multi} | ${l.modules.map(m => `${m.id}: ${m.total}`).join('<br>')} |`);
  lines.push('', '## Questions by type', '', '| Type | Count |', '|---|---|');
  for (const [t, n] of Object.entries(stats.byType)) lines.push(`| ${t} | ${n} |`);
  if (issues.length) { lines.push('', '## Validation issues', ''); for (const i of issues.slice(0, 300)) lines.push(`- **${i.severity}** \`${i.code}\` ${i.id}: ${i.message}`); }
  fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(root, 'docs', 'QUESTION_BANK_REPORT.md'), lines.join('\n') + '\n');
  console.log('Wrote docs/QUESTION_BANK_REPORT.md');
}
process.exit(errs.length ? 1 : 0);
